const data = {
    "happy birthday (Flyer)":{
      color: "#796F45",
      fontFamily: "adam script, cursive",
      postionX: 130,
      postionY: 1530,
      fontSize: 200,
      fontWeight: "bold",
    },
    "happy Birthday (Poster)":{
      color: "#A67D2E",
      fontFamily: "'Oregano', cursive",
      postionX: 150,
      postionY: 1250,
      fontSize:280,
      fontWeight: "normal",
    },
    "Pastel Cute Playful Happy Birthday Flyers Landscape A4":{
      color: "#2C3037",
      fontFamily: "bellaboo",
      postionX: 580,
      postionY: 900,
      fontSize:184,
      fontWeight: "bold",
    },
    "happy birthday instagram post":{
      color: "#87879E",
      fontFamily: "'Yeseva One', cursive",
      postionX: 220,
      postionY: 750,
      fontSize: 100,
      fontWeight: "normal",
    },
    "Yellow Border Happy Birthday Poster":{
      color: "#000000",
      fontFamily: "'Mr Dafoe', cursive",
      postionX: 320,
      postionY: 850,
      fontSize: 250,
      fontWeight: "normal",
    },
  }